### PR TITLE
Request blockBodies was asking by parent hash instead of it's own hash

### PR DESCRIPTION
**Pull request by AlanVerbner**
## Description

When asking for block bodies, the request message was being created using each block parentHash. That was causing two problems: 
- 1st body corresponds to the parent of the first node (we won't be able to use it)
- It wasn't being requested the last header item body

## Solution

As done in EthereumJ, we are now sending the hash of each rlp encoded header returned by `GetBlockHeaders`

### CODE REVIEW

**Comment by AlanVerbner** [comment]
@adamsmo I agree with you, will change it now

**Comment by adamsmo** [comment]
@AlanVerbner I resolved conflicts with phase/2

**Comment by AlanVerbner** [comment]
thanks @adamsmo .... is it ready to be merged?

**Comment by adamsmo** [comment]
@AlanVerbner I think we can merge it

**Pull request merged**
