### PR TITLE
ETCM-606 annotate test reports with slowest tests

### PR DESCRIPTION
**Pull request by jvdp**
The 50 slowest tests are reported as an annotation on BuildKite. Keeping this as a draft for a bit to see if https://github.com/buildkite-plugins/junit-annotate-buildkite-plugin/pull/144 will be merged.

### CODE REVIEW

**Comment by leo-bogastry** [comment]
Your PR was merged, so this one is not needed?

**Comment by jvdp** [comment]
> Your PR was merged, so this one is not needed?

There are still a bunch of slow tests so I think this will remain helpful for keeping an eye on it.

**Comment by leo-bogastry** [comment]
Hey @jvdp I still don't know much about Nix. Where can we see this test report?

**Comment by jvdp** [comment]
Valid question; you can see it on Buildkite:  https://buildkite.com/input-output-hk/mantis/builds/1884 (expand the "50 slowest tests" group.)

**Review by leo-bogastry — APPROVED** [review]
Cool 👍

**Pull request merged**
