### PR TITLE
[ETCM-349] remove snappy test package along with it's build.sbt record

### PR DESCRIPTION
**Pull request by dmitry-worker**
# Description

Unused `snappy` tests package had to be removed according to backlog task.

# Proposed Solution

Remove the folder itself
Cleanup the `build.sbt` file

### CODE REVIEW

**Review by lemastero — APPROVED** [review]

**Review by lemastero — CHANGES_REQUESTED** [review]
Could you sign the commits?

**Review by kapke — COMMENTED** [review]
Are there any unused dependencies maybe?

**Comment by dmitry-worker** [comment]
> Could you sign the commits?

I have actually signed the commit:
```
commit e92cbca30a8ccb235c8b65f07f42a7db3abd5b61 (HEAD -> feature/ETCM-349-remove-snappy-tests, origin/feature/ETCM-349-remove-snappy-tests)
gpg: Signature made Чт 17 дек 2020 21:00:09 MSK
gpg:                using RSA key 8EE1555B94AA9859824B7AF218F811D7C7A881A7
gpg: Good signature from "Dmitry Voronov <dmitry.voronov@iohk.io>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 8EE1 555B 94AA 9859 824B  7AF2 18F8 11D7 C7A8 81A7
Author: dmitry-worker <dzenmassta@gmail.com>
Date:   Thu Dec 17 21:00:09 2020 +0300

    feat - remove snappy test package along with it's build.sbt record
```

**Review by enriquerodbe — APPROVED** [review]
I think you signed the commits but GitHub says _Unverified_ because you have to add your public key to your GitHub account?

**Comment by dmitry-worker** [comment]
> I think you signed the commits but GitHub says _Unverified_ because you have to add your public key to your GitHub account?

Yep, and also commit was NOT under iohk email :( too bad for me

**Comment by dmitry-worker** [comment]
> Are there any unused dependencies maybe?

@kapke I guess not, the library itself is gonna be used further.

**Review by lemastero — APPROVED** [review]

**Pull request merged**
