### PR TITLE
Bump sbt version to 1.4.6

### PR DESCRIPTION
**Pull request by dmitry-worker**

### CODE REVIEW

**Comment by jonringer** [comment]
is the `./update-nix.sh` a do-able workflow?

**Comment by dmitry-worker** [comment]
> is the `./update-nix.sh` a do-able workflow?

Failed for me :( 
```
error: file 'nixpkgs' was not found in the Nix search path
```
(while i have Nix installed - maybe I messed up with the channels?) 
But nix-build succeeded (after manual update of depSha)
```
checking for references to /build/ in /nix/store/5yzh4mwjnr9ig6m0w5lkwynzczibb805-mantis-3.2.1...
/nix/store/5yzh4mwjnr9ig6m0w5lkwynzczibb805-mantis-3.2.1
```

**Comment by jonringer** [comment]
ah, interesting, usually the default channel is `<nixpkgs>`

**Review by jonringer — APPROVED** [review]

**Comment by jonringer** [comment]
buildkite passes so I think this is good to merge.

**Review by dzajkowski — APPROVED** [review]

**Pull request merged**
