### PR TITLE
Upgrade spongycastle version to 1.54

### PR DESCRIPTION
**Pull request by adamsmo**
Fix for using spongycastle API in incorrect way (passing to large IV vector)

### CODE REVIEW

**Comment by rtkaczyk** [comment]
Spongycastle appears not to be upgraded. Bad merge conflict resolution?

**Comment by adamsmo** [comment]
@rtkaczyk you mean build failure?
nope it was probably canceled
look here: https://travis-ci.org/input-output-hk/etc-client/builds/191627292

**Comment by rtkaczyk** [comment]
No, I mean that spongycastle has not been upgraded: https://github.com/input-output-hk/etc-client/blob/feature/spongycastleUpgrade/build.sbt#L10

**Comment by adamsmo** [comment]
yes, bad merge

**Pull request merged**
