### PR TITLE
[ETCM-259] sonar-scala [!pr]

### PR DESCRIPTION
**Pull request by biandratti**
# Description

Sonar scanner added:
https://sonar-scala.com/docs/about/what-is-sonar-scala

# Proposed Solution

Plugins added:
- "com.github.mwz" % "sbt-sonar" => it uses the embedded sonar-scanner API 
- "com.sksamuel.scapegoat" % "sbt-scapegoat" => is a plugin that integrates the scapegoat static code analysis library

# Testing

To test this approach you can read the following document.
https://sonar-scala.com/docs/setup/getting-started

- sbt clean coverage test
- sbt coverageReport
- sbt scapegoat => today we have different errors in this task. We need to work in the recommendation shown as output.
- sbt -Dsonar.host.url=http://localhost sonarScan

# Pending work

SonarQube instance

### CODE REVIEW

**Review by dmitry-worker — APPROVED** [review]
The plugin list size is becoming huge :)
By the way, there's a sonar-scoverage plugin:
https://github.com/RadoBuransky/sonar-scoverage-plugin

Since we use both of them - this might be useful

**Comment by enriquerodbe** [comment]
Cool! It would be nice to add a badge of the status in the README file and also the github PR decoration.

**Comment by biandratti** [comment]
I Share with you @dmitry-worker , the plugin list size is becoming huge.
In the sonar-scala documentation (https://github.com/mwz/sonar-scala) name the following plugin that you mention.
https://github.com/RadoBuransky/sonar-scoverage-plugin (sonar-scala utilized this plugin as inspiration)
But sonar-coverage-plugin requires SonarQube 5.1 (old version).
Cool! It would be nice to add a badge of the status in the README file and also the github PR decoration.


And how you mention, @enriquerodbe , the next step is to add badges of metrics in the README file and the github PR decoration :)

**Review by enriquerodbe — APPROVED** [review]

**Review by lemastero — APPROVED** [review]
LGTM 👍

**Comment by lemastero** [comment]
I would love to see WartRemover and ScalaFix. WartRemover encourages immutability & other useful FP things. But sometimes gets in the way.

ScalaFix is heavily used by ZIO ecosystem. It requires some work to configure it. But it can fix automatically some things.

But that is worth consider for the future.

**Review by ten15bit — APPROVED** [review]
Tested locally with docker :+1: 

We'll create another PR once the Sonarqube instance is available.

**Pull request merged**
