### PR TITLE
Added nodeId.keys to .gitignore

### PR DESCRIPTION
**Pull request by AlanVerbner**
Just that, nodeId.keys should not be pushed

### CODE REVIEW

**Comment by LukasGasior1** [comment]
actually, shouldn't we by default store it in `datadir`? maybe it's worth updating config by the occasion

**Comment by mcsherrylabs** [comment]
... I think that makes sense... arguments against?

**Comment by AlanVerbner** [comment]
@LukasGasior1 @mcsherrylabs just added `datadir` to config and updated all the keys to use it

**Comment by LukasGasior1** [comment]
LGTM!

**Pull request merged**
